version: "3.3"
services:
  rabbitmq:
    image: 'rabbitmq:3.12.2-management-alpine'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${FINE_SVC_RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${FINE_SVC_RABBIT_PASS}

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${FINE_SVC_MONGODB_DBNAME}
      MONGO_INITDB_ROOT_USERNAME: ${FINE_SVC_MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${FINE_SVC_MONGODB_PASSWORD}
    ports:
      - "${FINE_SVC_MONGODB_PORT}:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${FINE_SVC_MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${FINE_SVC_MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${FINE_SVC_MONGODB_USER}:${FINE_SVC_MONGODB_PASSWORD}@mongodb:27017
    depends_on:
      - mongodb
