server:
  port: ${FINE_SVC_SERVER_PORT}
spring:
  data:
    mongodb:
      user: ${FINE_SVC_MONGODB_USER}
      password: ${FINE_SVC_MONGODB_PASSWORD}
      uri: mongodb://${FINE_SVC_MONGODB_HOST}:${FINE_SVC_MONGODB_PORT}/${FINE_SVC_MONGODB_DBNAME}
